// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmnNsjO74ZAkKEYJhI7JqDvXfMH_uhZkE',
    appId: '1:124162161299:web:a0cb2eaa355c000c7f6b66',
    messagingSenderId: '124162161299',
    projectId: 'storystork',
    authDomain: 'storystork.firebaseapp.com',
    storageBucket: 'storystork.firebasestorage.app',
    measurementId: 'G-7ME969D0ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtMCub2f3jgVCfZ9EDUkvtEVb0UttqBXE',
    appId: '1:124162161299:android:2d13e11cb801aa1f7f6b66',
    messagingSenderId: '124162161299',
    projectId: 'storystork',
    storageBucket: 'storystork.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdX3Buq5CK5yTacdVMoHYFBN5gqhTKEFs',
    appId: '1:124162161299:ios:3139c762fb511f5d7f6b66',
    messagingSenderId: '124162161299',
    projectId: 'storystork',
    storageBucket: 'storystork.firebasestorage.app',
    iosBundleId: 'com.example.storystork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdX3Buq5CK5yTacdVMoHYFBN5gqhTKEFs',
    appId: '1:124162161299:ios:3139c762fb511f5d7f6b66',
    messagingSenderId: '124162161299',
    projectId: 'storystork',
    storageBucket: 'storystork.firebasestorage.app',
    iosBundleId: 'com.example.storystork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmnNsjO74ZAkKEYJhI7JqDvXfMH_uhZkE',
    appId: '1:124162161299:web:df7d494c6945a4747f6b66',
    messagingSenderId: '124162161299',
    projectId: 'storystork',
    authDomain: 'storystork.firebaseapp.com',
    storageBucket: 'storystork.firebasestorage.app',
    measurementId: 'G-MKH1WEJ45D',
  );

}